### PR TITLE
fix systemctl service name change

### PR DESCRIPTION
**Pull request by hanstananda**
Required to fix CI/CD pipeline

### CODE REVIEW

**Review by skurnia001 — DISMISSED** [review]
stop the old service before merging

**Comment by skurnia001** [comment]
what about config.yaml

**Comment by hanstananda** [comment]
> what about config.yaml

It should caught during try catch and just issue a warning if no `config.yaml` is found

**Comment by hanstananda** [comment]
> stop the old service before merging

Done alrd. The new service arld running under new name.

**Review by skurnia001 — APPROVED** [review]

**Pull request merged**
